const PDFDocument = require('pdfkit');

function buildPDF(heading, data, dataCallback, endCallback) {
  const doc = new PDFDocument();
  doc.on('data', dataCallback);
  doc.on('end', endCallback);
  doc.text(heading + '\n\n', {
    width: 410,
    align: 'center',
  });
  doc.text(data);
  doc.text('\n Generated by FoodprintLabs www.foodprintlabs.com', {
    width: 410,
    align: 'center',
  });
  doc.end();
}

module.exports = { buildPDF };
