// node ./tests/sequelize.js

const { Op, Sequelize } = require('sequelize');

var initModels = require('../models/init-models');
var sequelise = require('../config/db/db_sequelise');
var models = initModels(sequelise);

// Insert all produce
// Raw SQL: SELECT harvest_logid', 'harvest_produceName' FROM foodprint_harvest;
const InsertProduce = async () => {
  models.FoodprintProduce.bulkCreate([
    { pk: 1, produce_name: 'Artichoke', produce_type: 'FANCY VEG' },
    { pk: 2, produce_name: 'Asparagus', produce_type: 'FANCY VEG' },
    { pk: 3, produce_name: 'Basil', produce_type: 'HERBS' },
    { pk: 4, produce_name: 'Basil red', produce_type: 'HERBS' },
    { pk: 5, produce_name: 'Beans - Broad', produce_type: 'BASIC VEG' },
    { pk: 6, produce_name: 'Beans - Broad Tops', produce_type: 'BASIC VEG' },
    { pk: 7, produce_name: 'Beans bush ', produce_type: 'BASIC VEG' },
    { pk: 8, produce_name: 'Beans - Green', produce_type: 'BASIC VEG' },
    { pk: 9, produce_name: 'Beetroot', produce_type: 'BASIC VEG' },
    { pk: 10, produce_name: 'Beetroot - Baby /Golden', produce_type: 'BASIC VEG' },
    { pk: 11, produce_name: 'Brinjal', produce_type: 'BASIC VEG' },
    { pk: 12, produce_name: 'Broccoli', produce_type: 'OTHER VEG' },
    { pk: 13, produce_name: 'Brussels sprouts', produce_type: 'OTHER VEG' },
    { pk: 14, produce_name: 'Butternut', produce_type: 'BASIC VEG' },
    { pk: 15, produce_name: 'Cabbage', produce_type: 'BASIC VEG' },
    { pk: 16, produce_name: 'Cabbage - Baby green', produce_type: 'BASIC VEG' },
    { pk: 17, produce_name: 'Cabbage Chinese', produce_type: 'OTHER VEG' },
    { pk: 18, produce_name: 'Cabbage - Red', produce_type: 'OTHER VEG' },
    { pk: 19, produce_name: 'Cabbage sugar loaf', produce_type: 'OTHER VEG' },
    { pk: 20, produce_name: 'Carrots', produce_type: 'BASIC VEG' },
    { pk: 21, produce_name: 'Carrots - Baby', produce_type: 'BASIC VEG' },
    { pk: 22, produce_name: 'Carrots - Rainbow', produce_type: 'BASIC VEG' },
    { pk: 23, produce_name: 'Cauliflower', produce_type: 'BASIC VEG' },
    { pk: 24, produce_name: 'Celeriac', produce_type: 'OTHER VEG' },
    { pk: 25, produce_name: 'Celery - Soup', produce_type: 'OTHER VEG' },
    { pk: 26, produce_name: 'Celery - Table', produce_type: 'OTHER VEG' },
    { pk: 27, produce_name: 'Chillies', produce_type: 'FANCY VEG' },
    { pk: 28, produce_name: 'Chilies - Passion', produce_type: 'FANCY VEG' },
    { pk: 29, produce_name: 'Chillies bird eye', produce_type: 'FANCY VEG' },
    { pk: 30, produce_name: 'Chilies - Cayenne', produce_type: 'FANCY VEG' },
    { pk: 31, produce_name: 'Chilies - Cayenne Green', produce_type: 'FANCY VEG' },
    { pk: 32, produce_name: 'Chilies - Cayenne Red', produce_type: 'FANCY VEG' },
    { pk: 33, produce_name: 'Chillies green', produce_type: 'FANCY VEG' },
    { pk: 34, produce_name: 'Chillies habanero', produce_type: 'FANCY VEG' },
    { pk: 35, produce_name: 'Chilies - Jalepano', produce_type: 'FANCY VEG' },
    { pk: 36, produce_name: 'Chillies red', produce_type: 'FANCY VEG' },
    { pk: 37, produce_name: 'Chillies serrano', produce_type: 'FANCY VEG' },
    { pk: 38, produce_name: 'Chilies - Serrano Green', produce_type: 'FANCY VEG' },
    { pk: 39, produce_name: 'Chilies - Serrano Red', produce_type: 'FANCY VEG' },
    { pk: 40, produce_name: 'Chilies - Yellow', produce_type: 'FANCY VEG' },
    { pk: 41, produce_name: 'Chives', produce_type: 'HERBS' },
    { pk: 42, produce_name: 'Coriander', produce_type: 'HERBS' },
    { pk: 43, produce_name: 'Cucumbers', produce_type: 'OTHER VEG' },
    { pk: 44, produce_name: 'Dill', produce_type: 'HERBS' },
    { pk: 45, produce_name: 'Fennel', produce_type: 'OTHER VEG' },
    { pk: 46, produce_name: 'Garlic', produce_type: 'FANCY VEG' },
    { pk: 47, produce_name: 'Ginger', produce_type: 'FANCY VEG' },
    { pk: 48, produce_name: 'Gooseberry', produce_type: 'FANCY VEG' },
    { pk: 49, produce_name: 'Kale', produce_type: 'BASIC VEG' },
    { pk: 50, produce_name: 'Kale black', produce_type: 'BASIC VEG' },
    { pk: 51, produce_name: 'Kale - Curly', produce_type: 'BASIC VEG' },
    { pk: 52, produce_name: 'Kale - flat', produce_type: 'BASIC VEG' },
    { pk: 53, produce_name: 'Kale - Red', produce_type: 'BASIC VEG' },
    { pk: 54, produce_name: 'Kale - Russian', produce_type: 'BASIC VEG' },
    { pk: 55, produce_name: 'Khol Rabi', produce_type: 'OTHER VEG' },
    { pk: 56, produce_name: 'Khol Rabi - Purple', produce_type: 'OTHER VEG' },
    { pk: 57, produce_name: 'Lavender', produce_type: 'HERBS' },
    { pk: 58, produce_name: 'Leeks', produce_type: 'OTHER VEG' },
    { pk: 59, produce_name: 'Lemon', produce_type: 'FANCY VEG' },
    { pk: 60, produce_name: 'Lemongrass', produce_type: 'FANCY VEG' },
    { pk: 61, produce_name: 'Lettuce - Butterhead', produce_type: 'OTHER VEG' },
    { pk: 62, produce_name: 'Lettuce butter red', produce_type: 'OTHER VEG' },
    { pk: 63, produce_name: 'Lettuce - Cos Green', produce_type: 'OTHER VEG' },
    { pk: 64, produce_name: 'Lettuce cos baby', produce_type: 'OTHER VEG' },
    { pk: 65, produce_name: 'Lettuce - Cos red', produce_type: 'OTHER VEG' },
    { pk: 66, produce_name: 'Lettuce endive', produce_type: 'OTHER VEG' },
    { pk: 67, produce_name: 'Lettuce frilly', produce_type: 'OTHER VEG' },
    { pk: 68, produce_name: 'Lettuce - Frilly Green', produce_type: 'OTHER VEG' },
    { pk: 69, produce_name: 'Lettuce - Frilly Red', produce_type: 'OTHER VEG' },
    { pk: 70, produce_name: 'Lettuce - Gem', produce_type: 'OTHER VEG' },
    { pk: 71, produce_name: 'Lettuce - Baby Gem', produce_type: 'OTHER VEG' },
    { pk: 72, produce_name: 'Lettuce - Iceberg', produce_type: 'OTHER VEG' },
    { pk: 73, produce_name: 'Lettuce leafy red', produce_type: 'OTHER VEG' },
    { pk: 74, produce_name: 'Lettuce lollo rosso red', produce_type: 'OTHER VEG' },
    { pk: 75, produce_name: 'Lettuce - Oak Green', produce_type: 'OTHER VEG' },
    { pk: 76, produce_name: 'Lettuce - Mix', produce_type: 'OTHER VEG' },
    { pk: 77, produce_name: 'Lettuce - Oak Red', produce_type: 'OTHER VEG' },
    { pk: 78, produce_name: 'Marrow baby', produce_type: 'BASIC VEG' },
    { pk: 79, produce_name: 'Marrow baby Flowers', produce_type: 'BASIC VEG' },
    { pk: 80, produce_name: 'Mielies', produce_type: 'OTHER VEG' },
    { pk: 81, produce_name: 'Mint', produce_type: 'HERBS' },
    { pk: 82, produce_name: 'Mizuna Japanese Water Greens', produce_type: 'OTHER VEG' },
    { pk: 83, produce_name: 'Mustard', produce_type: 'OTHER VEG' },
    { pk: 84, produce_name: 'Mustard green', produce_type: 'OTHER VEG' },
    { pk: 85, produce_name: 'Mustard - red', produce_type: 'OTHER VEG' },
    { pk: 86, produce_name: 'Nausturtium', produce_type: 'HERBS' },
    { pk: 87, produce_name: 'Nettle', produce_type: 'FANCY VEG' },
    { pk: 88, produce_name: 'Okra', produce_type: 'FANCY VEG' },
    { pk: 89, produce_name: 'Onions red', produce_type: 'FANCY VEG' },
    { pk: 90, produce_name: 'Onions - Bunching', produce_type: 'OTHER VEG' },
    { pk: 91, produce_name: 'Onion - Bulb', produce_type: 'OTHER VEG' },
    { pk: 92, produce_name: 'Oregano', produce_type: 'HERBS' },
    { pk: 93, produce_name: 'Pak Choi', produce_type: 'BASIC VEG' },
    { pk: 94, produce_name: 'Parsley', produce_type: 'HERBS' },
    { pk: 95, produce_name: 'Parsley - Curly Moss', produce_type: 'HERBS' },
    { pk: 96, produce_name: 'Parsley - Flat', produce_type: 'HERBS' },
    { pk: 97, produce_name: 'Parsnip', produce_type: 'OTHER VEG' },
    { pk: 98, produce_name: 'Patty pans baby', produce_type: 'OTHER VEG' },
    { pk: 99, produce_name: 'Peas - Cascadia', produce_type: 'OTHER VEG' },
    { pk: 100, produce_name: 'Peas - Flat', produce_type: 'OTHER VEG' },
    { pk: 101, produce_name: 'Peas - Round', produce_type: 'OTHER VEG' },
    { pk: 102, produce_name: 'Peas shoots', produce_type: 'OTHER VEG' },
    { pk: 103, produce_name: 'Pepper colored', produce_type: 'FANCY VEG' },
    { pk: 104, produce_name: 'Pepper - Green', produce_type: 'BASIC VEG' },
    { pk: 105, produce_name: 'Pepper - Red', produce_type: 'FANCY VEG' },
    { pk: 106, produce_name: 'Pepper yellow', produce_type: 'FANCY VEG' },
    { pk: 107, produce_name: 'Potatoes', produce_type: 'BASIC VEG' },
    { pk: 108, produce_name: 'Potatoes baby', produce_type: 'BASIC VEG' },
    { pk: 109, produce_name: 'Pumpkin', produce_type: 'BASIC VEG' },
    { pk: 110, produce_name: 'Radish', produce_type: 'OTHER VEG' },
    { pk: 111, produce_name: 'Radish - Black', produce_type: 'OTHER VEG' },
    { pk: 112, produce_name: 'Radish - Daikon', produce_type: 'OTHER VEG' },
    { pk: 113, produce_name: 'Rape', produce_type: 'OTHER VEG' },
    { pk: 114, produce_name: 'Rhubarb', produce_type: 'FANCY VEG' },
    { pk: 115, produce_name: 'Rocket', produce_type: 'OTHER VEG' },
    { pk: 116, produce_name: 'Rocket wild', produce_type: 'OTHER VEG' },
    { pk: 117, produce_name: 'Rosemary', produce_type: 'HERBS' },
    { pk: 118, produce_name: 'Rosemary wild', produce_type: 'HERBS' },
    { pk: 119, produce_name: 'Sandkool', produce_type: 'FANCY VEG' },
    { pk: 120, produce_name: 'Sage', produce_type: 'HERBS' },
    { pk: 121, produce_name: 'Sage - African', produce_type: 'HERBS' },
    { pk: 122, produce_name: 'Salad mix', produce_type: 'OTHER VEG' },
    { pk: 123, produce_name: 'Shallot', produce_type: 'OTHER VEG' },
    { pk: 124, produce_name: 'Spring Onion - Red', produce_type: 'OTHER VEG' },
    { pk: 125, produce_name: 'Spinach Chard - Green', produce_type: 'BASIC VEG' },
    { pk: 126, produce_name: 'Spinach Chard - Rainbow', produce_type: 'BASIC VEG' },
    { pk: 127, produce_name: 'Spinach - English', produce_type: 'OTHER VEG' },
    { pk: 128, produce_name: 'Spinach - New Zealand', produce_type: 'OTHER VEG' },
    { pk: 129, produce_name: 'Spring Onion', produce_type: 'OTHER VEG' },
    { pk: 130, produce_name: 'Squash gem', produce_type: 'BASIC VEG' },
    { pk: 131, produce_name: 'Strawberries', produce_type: 'FANCY VEG' },
    { pk: 132, produce_name: 'Sweet Potatoes', produce_type: 'OTHER VEG' },
    { pk: 133, produce_name: 'Sweet Potatoes orange', produce_type: 'OTHER VEG' },
    { pk: 134, produce_name: 'Sweet Potatoes white', produce_type: 'OTHER VEG' },
    { pk: 135, produce_name: 'Tatsoi', produce_type: 'BASIC VEG' },
    { pk: 136, produce_name: 'Thyme', produce_type: 'HERBS' },
    { pk: 137, produce_name: 'Tomatoes', produce_type: 'BASIC VEG' },
    { pk: 138, produce_name: 'Tomatoes cherry', produce_type: 'BASIC VEG' },
    { pk: 139, produce_name: 'Turnips', produce_type: 'BASIC VEG' },
  ]).then(() => console.log('Produce data has been saved'));
};
const InsertProducePrice = async () => {
  models.FoodprintProducePrice.bulkCreate([
    {
      pk: 1,
      produce_name: 'Artichoke',
      produce_price: ' R53,75 ',
      produce_date: '29032022',
      produce_province: 'Western Cape',
    },
    {
      pk: 2,
      produce_name: 'Asparagus',
      produce_price: ' R279,50 ',
      produce_date: '29032023',
      produce_province: 'Western Cape',
    },
    {
      pk: 3,
      produce_name: 'Basil',
      produce_price: ' R86,00 ',
      produce_date: '29032024',
      produce_province: 'Western Cape',
    },
    {
      pk: 4,
      produce_name: 'Basil red',
      produce_price: ' R86,00 ',
      produce_date: '29032025',
      produce_province: 'Western Cape',
    },
    {
      pk: 5,
      produce_name: 'Beans - Broad',
      produce_price: ' R43,00 ',
      produce_date: '29032026',
      produce_province: 'Western Cape',
    },
    {
      pk: 6,
      produce_name: 'Beans - Broad Tops',
      produce_price: ' R86,00 ',
      produce_date: '29032027',
      produce_province: 'Western Cape',
    },
    {
      pk: 7,
      produce_name: 'Beans bush ',
      produce_price: ' R43,00 ',
      produce_date: '29032028',
      produce_province: 'Western Cape',
    },
    {
      pk: 8,
      produce_name: 'Beans - Green',
      produce_price: ' R43,00 ',
      produce_date: '29032029',
      produce_province: 'Western Cape',
    },
    {
      pk: 9,
      produce_name: 'Beetroot',
      produce_price: ' R19,35 ',
      produce_date: '29032030',
      produce_province: 'Western Cape',
    },
    {
      pk: 10,
      produce_name: 'Beetroot - Baby /Golden',
      produce_price: ' R53,75 ',
      produce_date: '29032031',
      produce_province: 'Western Cape',
    },
    {
      pk: 11,
      produce_name: 'Brinjal',
      produce_price: ' R37,63 ',
      produce_date: '29032032',
      produce_province: 'Western Cape',
    },
    {
      pk: 12,
      produce_name: 'Broccoli',
      produce_price: ' R39,78 ',
      produce_date: '29032033',
      produce_province: 'Western Cape',
    },
    {
      pk: 13,
      produce_name: 'Brussels sprouts',
      produce_price: ' R59,13 ',
      produce_date: '29032034',
      produce_province: 'Western Cape',
    },
    {
      pk: 14,
      produce_name: 'Butternut',
      produce_price: ' R17,20 ',
      produce_date: '29032035',
      produce_province: 'Western Cape',
    },
    {
      pk: 15,
      produce_name: 'Cabbage',
      produce_price: ' R19,35 ',
      produce_date: '29032036',
      produce_province: 'Western Cape',
    },
    {
      pk: 16,
      produce_name: 'Cabbage - Baby green',
      produce_price: ' R21,50 ',
      produce_date: '29032037',
      produce_province: 'Western Cape',
    },
    {
      pk: 17,
      produce_name: 'Cabbage Chinese',
      produce_price: ' R43,00 ',
      produce_date: '29032038',
      produce_province: 'Western Cape',
    },
    {
      pk: 18,
      produce_name: 'Cabbage - Red',
      produce_price: ' R43,00 ',
      produce_date: '29032039',
      produce_province: 'Western Cape',
    },
    {
      pk: 19,
      produce_name: 'Cabbage sugar loaf',
      produce_price: ' R19,35 ',
      produce_date: '29032040',
      produce_province: 'Western Cape',
    },
    {
      pk: 20,
      produce_name: 'Carrots',
      produce_price: ' R19,35 ',
      produce_date: '29032041',
      produce_province: 'Western Cape',
    },
    {
      pk: 21,
      produce_name: 'Carrots - Baby',
      produce_price: ' R45,15 ',
      produce_date: '29032042',
      produce_province: 'Western Cape',
    },
    {
      pk: 22,
      produce_name: 'Carrots - Rainbow',
      produce_price: ' R45,15 ',
      produce_date: '29032043',
      produce_province: 'Western Cape',
    },
    {
      pk: 23,
      produce_name: 'Cauliflower',
      produce_price: ' R37,63 ',
      produce_date: '29032044',
      produce_province: 'Western Cape',
    },
    {
      pk: 24,
      produce_name: 'Celeriac',
      produce_price: ' R118,25 ',
      produce_date: '29032045',
      produce_province: 'Western Cape',
    },
    {
      pk: 25,
      produce_name: 'Celery - Soup',
      produce_price: ' R37,63 ',
      produce_date: '29032046',
      produce_province: 'Western Cape',
    },
    {
      pk: 26,
      produce_name: 'Celery - Table',
      produce_price: ' R53,75 ',
      produce_date: '29032047',
      produce_province: 'Western Cape',
    },
    {
      pk: 27,
      produce_name: 'Chillies',
      produce_price: ' R64,50 ',
      produce_date: '29032048',
      produce_province: 'Western Cape',
    },
    {
      pk: 28,
      produce_name: 'Chilies - Passion',
      produce_price: ' R64,50 ',
      produce_date: '29032049',
      produce_province: 'Western Cape',
    },
    {
      pk: 29,
      produce_name: 'Chillies bird eye',
      produce_price: ' R69,88 ',
      produce_date: '29032050',
      produce_province: 'Western Cape',
    },
    {
      pk: 30,
      produce_name: 'Chilies - Cayenne',
      produce_price: ' R69,88 ',
      produce_date: '29032051',
      produce_province: 'Western Cape',
    },
    {
      pk: 31,
      produce_name: 'Chilies - Cayenne Green',
      produce_price: ' R69,88 ',
      produce_date: '29032052',
      produce_province: 'Western Cape',
    },
    {
      pk: 32,
      produce_name: 'Chilies - Cayenne Red',
      produce_price: ' R64,50 ',
      produce_date: '29032053',
      produce_province: 'Western Cape',
    },
    {
      pk: 33,
      produce_name: 'Chillies green',
      produce_price: ' R64,50 ',
      produce_date: '29032054',
      produce_province: 'Western Cape',
    },
    {
      pk: 34,
      produce_name: 'Chillies habanero',
      produce_price: ' R64,50 ',
      produce_date: '29032055',
      produce_province: 'Western Cape',
    },
    {
      pk: 35,
      produce_name: 'Chilies - Jalepano',
      produce_price: ' R64,50 ',
      produce_date: '29032056',
      produce_province: 'Western Cape',
    },
    {
      pk: 36,
      produce_name: 'Chillies red',
      produce_price: ' R64,50 ',
      produce_date: '29032057',
      produce_province: 'Western Cape',
    },
    {
      pk: 37,
      produce_name: 'Chillies serrano',
      produce_price: ' R64,50 ',
      produce_date: '29032058',
      produce_province: 'Western Cape',
    },
    {
      pk: 38,
      produce_name: 'Chilies - Serrano Green',
      produce_price: ' R64,50 ',
      produce_date: '29032059',
      produce_province: 'Western Cape',
    },
    {
      pk: 39,
      produce_name: 'Chilies - Serrano Red',
      produce_price: ' R64,50 ',
      produce_date: '29032060',
      produce_province: 'Western Cape',
    },
    {
      pk: 40,
      produce_name: 'Chilies - Yellow',
      produce_price: ' R69,88 ',
      produce_date: '29032061',
      produce_province: 'Western Cape',
    },
    {
      pk: 41,
      produce_name: 'Chives',
      produce_price: ' R86,00 ',
      produce_date: '29032062',
      produce_province: 'Western Cape',
    },
    {
      pk: 42,
      produce_name: 'Coriander',
      produce_price: ' R86,00 ',
      produce_date: '29032063',
      produce_province: 'Western Cape',
    },
    {
      pk: 43,
      produce_name: 'Cucumbers',
      produce_price: ' R26,88 ',
      produce_date: '29032064',
      produce_province: 'Western Cape',
    },
    {
      pk: 44,
      produce_name: 'Dill',
      produce_price: ' R86,00 ',
      produce_date: '29032065',
      produce_province: 'Western Cape',
    },
    {
      pk: 45,
      produce_name: 'Fennel',
      produce_price: ' R45,15 ',
      produce_date: '29032066',
      produce_province: 'Western Cape',
    },
    {
      pk: 46,
      produce_name: 'Garlic',
      produce_price: ' R64,50 ',
      produce_date: '29032067',
      produce_province: 'Western Cape',
    },
    {
      pk: 47,
      produce_name: 'Ginger',
      produce_price: ' R64,50 ',
      produce_date: '29032068',
      produce_province: 'Western Cape',
    },
    {
      pk: 48,
      produce_name: 'Gooseberry',
      produce_price: ' R86,00 ',
      produce_date: '29032069',
      produce_province: 'Western Cape',
    },
    {
      pk: 49,
      produce_name: 'Kale',
      produce_price: ' R45,15 ',
      produce_date: '29032070',
      produce_province: 'Western Cape',
    },
    {
      pk: 50,
      produce_name: 'Kale black',
      produce_price: ' R45,15 ',
      produce_date: '29032071',
      produce_province: 'Western Cape',
    },
    {
      pk: 51,
      produce_name: 'Kale - Curly',
      produce_price: ' R45,15 ',
      produce_date: '29032072',
      produce_province: 'Western Cape',
    },
    {
      pk: 52,
      produce_name: 'Kale - flat',
      produce_price: ' R45,15 ',
      produce_date: '29032073',
      produce_province: 'Western Cape',
    },
    {
      pk: 53,
      produce_name: 'Kale - Red',
      produce_price: ' R53,75 ',
      produce_date: '29032074',
      produce_province: 'Western Cape',
    },
    {
      pk: 54,
      produce_name: 'Kale - Russian',
      produce_price: ' R45,15 ',
      produce_date: '29032075',
      produce_province: 'Western Cape',
    },
    {
      pk: 55,
      produce_name: 'Khol Rabi',
      produce_price: ' R26,88 ',
      produce_date: '29032076',
      produce_province: 'Western Cape',
    },
    {
      pk: 56,
      produce_name: 'Khol Rabi - Purple',
      produce_price: ' R32,25 ',
      produce_date: '29032077',
      produce_province: 'Western Cape',
    },
    {
      pk: 57,
      produce_name: 'Lavender',
      produce_price: ' R86,00 ',
      produce_date: '29032078',
      produce_province: 'Western Cape',
    },
    {
      pk: 58,
      produce_name: 'Leeks',
      produce_price: ' R22,58 ',
      produce_date: '29032079',
      produce_province: 'Western Cape',
    },
    {
      pk: 59,
      produce_name: 'Lemon',
      produce_price: ' R17,20 ',
      produce_date: '29032080',
      produce_province: 'Western Cape',
    },
    {
      pk: 60,
      produce_name: 'Lemongrass',
      produce_price: ' R96,75 ',
      produce_date: '29032081',
      produce_province: 'Western Cape',
    },
    {
      pk: 61,
      produce_name: 'Lettuce - Butterhead',
      produce_price: ' R43,00 ',
      produce_date: '29032082',
      produce_province: 'Western Cape',
    },
    {
      pk: 62,
      produce_name: 'Lettuce butter red',
      produce_price: ' R43,00 ',
      produce_date: '29032083',
      produce_province: 'Western Cape',
    },
    {
      pk: 63,
      produce_name: 'Lettuce - Cos Green',
      produce_price: ' R43,00 ',
      produce_date: '29032084',
      produce_province: 'Western Cape',
    },
    {
      pk: 64,
      produce_name: 'Lettuce cos baby',
      produce_price: ' R43,00 ',
      produce_date: '29032085',
      produce_province: 'Western Cape',
    },
    {
      pk: 65,
      produce_name: 'Lettuce - Cos red',
      produce_price: ' R43,00 ',
      produce_date: '29032086',
      produce_province: 'Western Cape',
    },
    {
      pk: 66,
      produce_name: 'Lettuce endive',
      produce_price: ' R45,15 ',
      produce_date: '29032087',
      produce_province: 'Western Cape',
    },
    {
      pk: 67,
      produce_name: 'Lettuce frilly',
      produce_price: ' R21,50 ',
      produce_date: '29032088',
      produce_province: 'Western Cape',
    },
    {
      pk: 68,
      produce_name: 'Lettuce - Frilly Green',
      produce_price: ' R21,50 ',
      produce_date: '29032089',
      produce_province: 'Western Cape',
    },
    {
      pk: 69,
      produce_name: 'Lettuce - Frilly Red',
      produce_price: ' R21,50 ',
      produce_date: '29032090',
      produce_province: 'Western Cape',
    },
    {
      pk: 70,
      produce_name: 'Lettuce - Gem',
      produce_price: ' R21,50 ',
      produce_date: '29032091',
      produce_province: 'Western Cape',
    },
    {
      pk: 71,
      produce_name: 'Lettuce - Baby Gem',
      produce_price: ' R21,50 ',
      produce_date: '29032092',
      produce_province: 'Western Cape',
    },
    {
      pk: 72,
      produce_name: 'Lettuce - Iceberg',
      produce_price: ' R21,50 ',
      produce_date: '29032093',
      produce_province: 'Western Cape',
    },
    {
      pk: 73,
      produce_name: 'Lettuce leafy red',
      produce_price: ' R21,50 ',
      produce_date: '29032094',
      produce_province: 'Western Cape',
    },
    {
      pk: 74,
      produce_name: 'Lettuce lollo rosso red',
      produce_price: ' R21,50 ',
      produce_date: '29032095',
      produce_province: 'Western Cape',
    },
    {
      pk: 75,
      produce_name: 'Lettuce - Oak Green',
      produce_price: ' R21,50 ',
      produce_date: '29032096',
      produce_province: 'Western Cape',
    },
    {
      pk: 76,
      produce_name: 'Lettuce - Mix',
      produce_price: ' R21,50 ',
      produce_date: '29032097',
      produce_province: 'Western Cape',
    },
    {
      pk: 77,
      produce_name: 'Lettuce - Oak Red',
      produce_price: ' R21,50 ',
      produce_date: '29032098',
      produce_province: 'Western Cape',
    },
    {
      pk: 78,
      produce_name: 'Marrow baby',
      produce_price: ' R32,25 ',
      produce_date: '29032099',
      produce_province: 'Western Cape',
    },
    {
      pk: 79,
      produce_name: 'Marrow baby Flowers',
      produce_price: ' R32,25 ',
      produce_date: '29032100',
      produce_province: 'Western Cape',
    },
    {
      pk: 80,
      produce_name: 'Mielies',
      produce_price: ' R17,20 ',
      produce_date: '29032101',
      produce_province: 'Western Cape',
    },
    {
      pk: 81,
      produce_name: 'Mint',
      produce_price: ' R86,00 ',
      produce_date: '29032102',
      produce_province: 'Western Cape',
    },
    {
      pk: 82,
      produce_name:
        'Mizuna produce_price:{ pk:Japaprodproduce_date:uce_name:nesproduce_province:e Water Greens}',
      produce_price: ' R43,00 ',
      produce_date: '29032103',
      produce_province: 'Western Cape',
    },
    {
      pk: 83,
      produce_name: 'Mustard',
      produce_price: ' R21,50 ',
      produce_date: '29032104',
      produce_province: 'Western Cape',
    },
    {
      pk: 84,
      produce_name: 'Mustard green',
      produce_price: ' R21,50 ',
      produce_date: '29032105',
      produce_province: 'Western Cape',
    },
    {
      pk: 85,
      produce_name: 'Mustard - red',
      produce_price: ' R21,50 ',
      produce_date: '29032106',
      produce_province: 'Western Cape',
    },
    {
      pk: 86,
      produce_name: 'Nausturtium',
      produce_price: ' R21,50 ',
      produce_date: '29032107',
      produce_province: 'Western Cape',
    },
    {
      pk: 87,
      produce_name: 'Nettle',
      produce_price: ' R17,20 ',
      produce_date: '29032108',
      produce_province: 'Western Cape',
    },
    {
      pk: 88,
      produce_name: 'Okra',
      produce_price: ' R26,88 ',
      produce_date: '29032109',
      produce_province: 'Western Cape',
    },
    {
      pk: 89,
      produce_name: 'Onions red',
      produce_price: ' R17,20 ',
      produce_date: '29032110',
      produce_province: 'Western Cape',
    },
    {
      pk: 90,
      produce_name: 'Onions - Bunching',
      produce_price: ' R34,40 ',
      produce_date: '29032111',
      produce_province: 'Western Cape',
    },
    {
      pk: 91,
      produce_name: 'Onion - Bulb',
      produce_price: ' R12,90 ',
      produce_date: '29032112',
      produce_province: 'Western Cape',
    },
    {
      pk: 92,
      produce_name: 'Oregano',
      produce_price: ' R86,00 ',
      produce_date: '29032113',
      produce_province: 'Western Cape',
    },
    {
      pk: 93,
      produce_name: 'Pak Choi',
      produce_price: ' R43,00 ',
      produce_date: '29032114',
      produce_province: 'Western Cape',
    },
    {
      pk: 94,
      produce_name: 'Parsley',
      produce_price: ' R86,00 ',
      produce_date: '29032115',
      produce_province: 'Western Cape',
    },
    {
      pk: 95,
      produce_name: 'Parsley - Curly Moss',
      produce_price: ' R86,00 ',
      produce_date: '29032116',
      produce_province: 'Western Cape',
    },
    {
      pk: 96,
      produce_name: 'Parsley - Flat',
      produce_price: ' R86,00 ',
      produce_date: '29032117',
      produce_province: 'Western Cape',
    },
    {
      pk: 97,
      produce_name: 'Parsnip',
      produce_price: ' R86,00 ',
      produce_date: '29032118',
      produce_province: 'Western Cape',
    },
    {
      pk: 98,
      produce_name: 'Patty pans baby',
      produce_price: ' R43,00 ',
      produce_date: '29032119',
      produce_province: 'Western Cape',
    },
    {
      pk: 99,
      produce_name: 'Peas - Cascadia',
      produce_price: ' R129,00 ',
      produce_date: '29032120',
      produce_province: 'Western Cape',
    },
    {
      pk: 100,
      produce_name: 'Peas - Flat',
      produce_price: ' R129,00 ',
      produce_date: '29032121',
      produce_province: 'Western Cape',
    },
    {
      pk: 101,
      produce_name: 'Peas - Round',
      produce_price: ' R64,50 ',
      produce_date: '29032122',
      produce_province: 'Western Cape',
    },
    {
      pk: 102,
      produce_name: 'Peas shoots',
      produce_price: ' R96,75 ',
      produce_date: '29032123',
      produce_province: 'Western Cape',
    },
    {
      pk: 103,
      produce_name: 'Pepper colored',
      produce_price: ' R37,63 ',
      produce_date: '29032124',
      produce_province: 'Western Cape',
    },
    {
      pk: 104,
      produce_name: 'Pepper - Green',
      produce_price: ' R32,25 ',
      produce_date: '29032125',
      produce_province: 'Western Cape',
    },
    {
      pk: 105,
      produce_name: 'Pepper - Red',
      produce_price: ' R37,63 ',
      produce_date: '29032126',
      produce_province: 'Western Cape',
    },
    {
      pk: 106,
      produce_name: 'Pepper yellow',
      produce_price: ' R37,63 ',
      produce_date: '29032127',
      produce_province: 'Western Cape',
    },
    {
      pk: 107,
      produce_name: 'Potatoes',
      produce_price: ' R12,90 ',
      produce_date: '29032128',
      produce_province: 'Western Cape',
    },
    {
      pk: 108,
      produce_name: 'Potatoes baby',
      produce_price: ' R12,90 ',
      produce_date: '29032129',
      produce_province: 'Western Cape',
    },
    {
      pk: 109,
      produce_name: 'Pumpkin',
      produce_price: ' R17,20 ',
      produce_date: '29032130',
      produce_province: 'Western Cape',
    },
    {
      pk: 110,
      produce_name: 'Radish',
      produce_price: ' R37,63 ',
      produce_date: '29032131',
      produce_province: 'Western Cape',
    },
    {
      pk: 111,
      produce_name: 'Radish - Black',
      produce_price: ' R37,63 ',
      produce_date: '29032132',
      produce_province: 'Western Cape',
    },
    {
      pk: 112,
      produce_name: 'Radish - Daikon',
      produce_price: ' R37,63 ',
      produce_date: '29032133',
      produce_province: 'Western Cape',
    },
    {
      pk: 113,
      produce_name: 'Rape',
      produce_price: ' R21,50 ',
      produce_date: '29032134',
      produce_province: 'Western Cape',
    },
    {
      pk: 114,
      produce_name: 'Rhubarb',
      produce_price: ' R43,00 ',
      produce_date: '29032135',
      produce_province: 'Western Cape',
    },
    {
      pk: 115,
      produce_name: 'Rocket',
      produce_price: ' R86,00 ',
      produce_date: '29032136',
      produce_province: 'Western Cape',
    },
    {
      pk: 116,
      produce_name: 'Rocket wild',
      produce_price: ' R86,00 ',
      produce_date: '29032137',
      produce_province: 'Western Cape',
    },
    {
      pk: 117,
      produce_name: 'Rosemary',
      produce_price: ' R86,00 ',
      produce_date: '29032138',
      produce_province: 'Western Cape',
    },
    {
      pk: 118,
      produce_name: 'Rosemary wild',
      produce_price: ' R86,00 ',
      produce_date: '29032139',
      produce_province: 'Western Cape',
    },
    {
      pk: 119,
      produce_name: 'Sandkool',
      produce_price: ' R129,00 ',
      produce_date: '29032140',
      produce_province: 'Western Cape',
    },
    {
      pk: 120,
      produce_name: 'Sage',
      produce_price: ' R86,00 ',
      produce_date: '29032141',
      produce_province: 'Western Cape',
    },
    {
      pk: 121,
      produce_name: 'Sage - African',
      produce_price: ' R86,00 ',
      produce_date: '29032142',
      produce_province: 'Western Cape',
    },
    {
      pk: 122,
      produce_name: 'Salad mix',
      produce_price: ' R43,00 ',
      produce_date: '29032143',
      produce_province: 'Western Cape',
    },
    {
      pk: 123,
      produce_name: 'Shallot',
      produce_price: ' R86,00 ',
      produce_date: '29032144',
      produce_province: 'Western Cape',
    },
    {
      pk: 124,
      produce_name: 'Spring Onion - Red',
      produce_price: ' R21,50 ',
      produce_date: '29032145',
      produce_province: 'Western Cape',
    },
    {
      pk: 125,
      produce_name: 'Spinach Chard - Green',
      produce_price: ' R21,50 ',
      produce_date: '29032146',
      produce_province: 'Western Cape',
    },
    {
      pk: 126,
      produce_name: 'Spinach Chard - Rainbow',
      produce_price: ' R37,63 ',
      produce_date: '29032147',
      produce_province: 'Western Cape',
    },
    {
      pk: 127,
      produce_name: 'Spinach - English',
      produce_price: ' R53,75 ',
      produce_date: '29032148',
      produce_province: 'Western Cape',
    },
    {
      pk: 128,
      produce_name: 'Spinach - New Zealand',
      produce_price: ' R53,75 ',
      produce_date: '29032149',
      produce_province: 'Western Cape',
    },
    {
      pk: 129,
      produce_name: 'Spring Onion',
      produce_price: ' R34,40 ',
      produce_date: '29032150',
      produce_province: 'Western Cape',
    },
    {
      pk: 130,
      produce_name: 'Squash gem',
      produce_price: ' R43,00 ',
      produce_date: '29032151',
      produce_province: 'Western Cape',
    },
    {
      pk: 131,
      produce_name: 'Strawberries',
      produce_price: ' R129,00 ',
      produce_date: '29032152',
      produce_province: 'Western Cape',
    },
    {
      pk: 132,
      produce_name: 'Sweet Potatoes',
      produce_price: ' R17,20 ',
      produce_date: '29032153',
      produce_province: 'Western Cape',
    },
    {
      pk: 133,
      produce_name: 'Sweet Potatoes orange',
      produce_price: ' R17,20 ',
      produce_date: '29032154',
      produce_province: 'Western Cape',
    },
    {
      pk: 134,
      produce_name: 'Sweet Potatoes white',
      produce_price: ' R17,20 ',
      produce_date: '29032155',
      produce_province: 'Western Cape',
    },
    {
      pk: 135,
      produce_name: 'Tatsoi',
      produce_price: ' R21,50 ',
      produce_date: '29032156',
      produce_province: 'Western Cape',
    },
    {
      pk: 136,
      produce_name: 'Thyme',
      produce_price: ' R86,00 ',
      produce_date: '29032157',
      produce_province: 'Western Cape',
    },
    {
      pk: 137,
      produce_name: 'Tomatoes',
      produce_price: ' R43,00 ',
      produce_date: '29032158',
      produce_province: 'Western Cape',
    },
    {
      pk: 138,
      produce_name: 'Tomatoes cherry',
      produce_price: ' R44,00 ',
      produce_date: '29032159',
      produce_province: 'Western Cape',
    },
    {
      pk: 139,
      produce_name: 'Turnips',
      produce_price: ' R17,20 ',
      produce_date: '29032160',
      produce_province: 'Western Cape',
    },
  ]).then(() => console.log('Produce Price data has been saved'));
};

const createTables = async () => {
  models.FoodprintProduce.sync();
  models.FoodprintProducePrice.sync();
};

const run = async () => {
  //await createTables();
  await InsertProduce();
  await InsertProducePrice();
  await process.exit();
};

run();
